version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aqa_shop
    volumes:
      - postgres_data:/var/lib/postgresql/data

  gate-simulator:
    build: ./gate-simulator
    ports:
      - "9999:9999"
    working_dir: /app
    command: npm start

volumes:
  mysql_data:
  postgres_data: