name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 1) Ставим JDK 17, чтобы совпадала с toolchain { languageVersion = 17 } в build.gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 2) Запускаем SUT в фоне
      - name: Start SUT
        run: java -jar ./artifacts/app-ibank-build-for-testers.jar &

      # 3) Ждём, пока SUT реально поднимется (на порту 9999).
      #    Если у вас нет nc (netcat), замените на sleep 15 или sleep 20
      - name: Wait for SUT
        run: |
          echo "Waiting for SUT to start..."
          for i in {1..10}; do
            if nc -z localhost 9999; then
              echo "SUT is up!"
              break
            fi
            echo "Still waiting..."
            sleep 3
          done

      # 4) Запускаем тесты в headless-режиме
      - name: Build with Gradle
        run: ./gradlew test --info -Dselenide.headless=true